// proto文件语法版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpc.proto

package testrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求参数
type PushReqArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=Room,proto3" json:"Room,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushReqArgs) Reset() {
	*x = PushReqArgs{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushReqArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReqArgs) ProtoMessage() {}

func (x *PushReqArgs) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReqArgs.ProtoReflect.Descriptor instead.
func (*PushReqArgs) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *PushReqArgs) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *PushReqArgs) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PushReqArgs) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PushReqArgs) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 响应参数
type PushRespArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRespArgs) Reset() {
	*x = PushRespArgs{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRespArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRespArgs) ProtoMessage() {}

func (x *PushRespArgs) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRespArgs.ProtoReflect.Descriptor instead.
func (*PushRespArgs) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *PushRespArgs) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PushRespArgs) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\"[\n" +
	"\vPushReqArgs\x12\x12\n" +
	"\x04Room\x18\x01 \x01(\tR\x04Room\x12\x12\n" +
	"\x04User\x18\x02 \x01(\tR\x04User\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\tR\x04Type\x12\x10\n" +
	"\x03Msg\x18\x04 \x01(\tR\x03Msg\"4\n" +
	"\fPushRespArgs\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x05R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg2;\n" +
	"\vPushRequest\x12,\n" +
	"\vPushRequest\x12\f.PushReqArgs\x1a\r.PushRespArgs\"\x00B\vZ\t.;testrpcb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_proto_goTypes = []any{
	(*PushReqArgs)(nil),  // 0: PushReqArgs
	(*PushRespArgs)(nil), // 1: PushRespArgs
}
var file_rpc_proto_depIdxs = []int32{
	0, // 0: PushRequest.PushRequest:input_type -> PushReqArgs
	1, // 1: PushRequest.PushRequest:output_type -> PushRespArgs
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
