// proto文件语法版本

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: rpc.proto

package testrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushRequest_PushRequest_FullMethodName = "/PushRequest/PushRequest"
)

// PushRequestClient is the client API for PushRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 方法名称
type PushRequestClient interface {
	PushRequest(ctx context.Context, in *PushReqArgs, opts ...grpc.CallOption) (*PushRespArgs, error)
}

type pushRequestClient struct {
	cc grpc.ClientConnInterface
}

func NewPushRequestClient(cc grpc.ClientConnInterface) PushRequestClient {
	return &pushRequestClient{cc}
}

func (c *pushRequestClient) PushRequest(ctx context.Context, in *PushReqArgs, opts ...grpc.CallOption) (*PushRespArgs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushRespArgs)
	err := c.cc.Invoke(ctx, PushRequest_PushRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushRequestServer is the server API for PushRequest service.
// All implementations must embed UnimplementedPushRequestServer
// for forward compatibility.
//
// 方法名称
type PushRequestServer interface {
	PushRequest(context.Context, *PushReqArgs) (*PushRespArgs, error)
	mustEmbedUnimplementedPushRequestServer()
}

// UnimplementedPushRequestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushRequestServer struct{}

func (UnimplementedPushRequestServer) PushRequest(context.Context, *PushReqArgs) (*PushRespArgs, error) {
	return nil, status.Error(codes.Unimplemented, "method PushRequest not implemented")
}
func (UnimplementedPushRequestServer) mustEmbedUnimplementedPushRequestServer() {}
func (UnimplementedPushRequestServer) testEmbeddedByValue()                     {}

// UnsafePushRequestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushRequestServer will
// result in compilation errors.
type UnsafePushRequestServer interface {
	mustEmbedUnimplementedPushRequestServer()
}

func RegisterPushRequestServer(s grpc.ServiceRegistrar, srv PushRequestServer) {
	// If the following call panics, it indicates UnimplementedPushRequestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushRequest_ServiceDesc, srv)
}

func _PushRequest_PushRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushReqArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushRequestServer).PushRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushRequest_PushRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushRequestServer).PushRequest(ctx, req.(*PushReqArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// PushRequest_ServiceDesc is the grpc.ServiceDesc for PushRequest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushRequest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PushRequest",
	HandlerType: (*PushRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushRequest",
			Handler:    _PushRequest_PushRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
