// proto文件语法版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpc.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 推流请求/响应参数
type RtcPushReqArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=Room,proto3" json:"Room,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcPushReqArgs) Reset() {
	*x = RtcPushReqArgs{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcPushReqArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcPushReqArgs) ProtoMessage() {}

func (x *RtcPushReqArgs) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcPushReqArgs.ProtoReflect.Descriptor instead.
func (*RtcPushReqArgs) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RtcPushReqArgs) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *RtcPushReqArgs) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RtcPushReqArgs) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RtcPushReqArgs) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RtcPushRespArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcPushRespArgs) Reset() {
	*x = RtcPushRespArgs{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcPushRespArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcPushRespArgs) ProtoMessage() {}

func (x *RtcPushRespArgs) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcPushRespArgs.ProtoReflect.Descriptor instead.
func (*RtcPushRespArgs) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RtcPushRespArgs) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RtcPushRespArgs) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\"^\n" +
	"\x0eRtcPushReqArgs\x12\x12\n" +
	"\x04Room\x18\x01 \x01(\tR\x04Room\x12\x12\n" +
	"\x04User\x18\x02 \x01(\tR\x04User\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\tR\x04Type\x12\x10\n" +
	"\x03Msg\x18\x04 \x01(\tR\x03Msg\"7\n" +
	"\x0fRtcPushRespArgs\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg29\n" +
	"\aRpcConn\x12.\n" +
	"\aRtcPush\x12\x0f.RtcPushReqArgs\x1a\x10.RtcPushRespArgs\"\x00B\aZ\x05.;rpcb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_proto_goTypes = []any{
	(*RtcPushReqArgs)(nil),  // 0: RtcPushReqArgs
	(*RtcPushRespArgs)(nil), // 1: RtcPushRespArgs
}
var file_rpc_proto_depIdxs = []int32{
	0, // 0: RpcConn.RtcPush:input_type -> RtcPushReqArgs
	1, // 1: RpcConn.RtcPush:output_type -> RtcPushRespArgs
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
